### ISSUE TITLE
ImportError: cannot import name Upcase

### ISSUE THREAD

**Issue by timdp** [mathcamp/dql#4]
```
> dql
Traceback (most recent call last):
  File "C:\Python27\Scripts\dql-script.py", line 9, in <module>
    load_entry_point('dql==0.5.11', 'console_scripts', 'dql')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2345, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\dql\__init__.py", line 6, in <module>
    from .cli import DQLClient
  File "c:\python27\lib\site-packages\dql\cli.py", line 15, in <module>
    from .engine import FragmentEngine
  File "c:\python27\lib\site-packages\dql\engine.py", line 23, in <module>
    from .grammar import parser, line_parser
  File "c:\python27\lib\site-packages\dql\grammar\__init__.py", line 6, in <module>
    from .common import (from_, table, var, value, table_key, into, type_, upkey,
  File "c:\python27\lib\site-packages\dql\grammar\common.py", line 2, in <module>
    from pyparsing import (Word, Upcase, Optional, Combine, Group, alphas, nums,
ImportError: cannot import name Upcase
```

I get the same with Python 3. If I downgrade pyparsing to 1.5.7, I get a different error: "AttributeError: 'NoneType' object has no attribute 'setResultsName'". Could it be that you have a dependency versioning problem?

**Comment by stevearc** [comment]
I just ran into this myself yesterday. I have a fix coming, but I'm trying to sneak a couple other fixes in with it. For now you can get it working again with `pip install pyparsing==2.0.6`.

**Comment by stevearc** [comment]
Released [0.5.12](https://pypi.python.org/pypi/dql/0.5.12) which fixes this issue

**Comment by timdp** [comment]
Thanks! :+1:

Unfortunately, now I'm getting "ImportError: No module named _curses", but that seems like a Windows-specific thing.

**Comment by stevearc** [comment]
Aw, that sucks. We're only using curses for an overly-fancy new throughput monitor. I'll see if I can get a version to install nicely on Windows without curses.

**Comment by stevearc** [comment]
New version released. Give [0.5.14](https://pypi.python.org/pypi/dql/0.5.14) a try.

**Comment by timdp** [comment]
ImportError: No module named fcntl.

Looks like you like Windows-incompatible dependencies. :stuck_out_tongue:

**Comment by stevearc** [comment]
Don't have a windows developer environment set up and travis-ci doesn't have windows builds
`¯\_(ツ)_/¯`

I'll set up python and give it a whirl on my windows machine, but I'm going out of town and I won't be able to do it until Monday at the earliest.

**Comment by timdp** [comment]
That's cool. I appreciate your persistence. :wink:

**Comment by stevearc** [comment]
Okay, I think I've found and handled all the imports that fail on Windows. Try version [0.5.15](https://pypi.python.org/pypi/dql/0.5.15)

**Comment by timdp** [comment]
Indeed, you have! Thanks! :+1:
